# Generated by Django 4.2.3 on 2024-01-04 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('vendor_display_name', models.CharField(max_length=255)),
                ('vendor_email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=15)),
                ('company_name', models.CharField(max_length=255)),
                ('skype_name_number', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('gst_treatment', models.CharField(max_length=255)),
                ('gst_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('opening_balance_type', models.CharField(max_length=255)),
                ('opening_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('source_of_supply', models.CharField(max_length=255)),
                ('billing_attention', models.CharField(max_length=255)),
                ('billing_address', models.TextField()),
                ('billing_city', models.CharField(max_length=255)),
                ('billing_state', models.CharField(max_length=255)),
                ('billing_country', models.CharField(max_length=255)),
                ('billing_pin_code', models.CharField(max_length=10)),
                ('billing_phone', models.CharField(max_length=15)),
                ('billing_fax', models.CharField(max_length=15)),
                ('shipping_attention', models.CharField(max_length=255)),
                ('shipping_address', models.TextField()),
                ('shipping_city', models.CharField(max_length=255)),
                ('shipping_state', models.CharField(max_length=255)),
                ('shipping_country', models.CharField(max_length=255)),
                ('shipping_pin_code', models.CharField(max_length=10)),
                ('shipping_phone', models.CharField(max_length=15)),
                ('shipping_fax', models.CharField(max_length=15)),
                ('remarks', models.TextField()),
                ('vendor_status', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.company')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.paymentterm')),
            ],
        ),
        migrations.CreateModel(
            name='VendorHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('action', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.company')),
                ('login_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerContactPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('work_phone', models.CharField(max_length=15)),
                ('mobile', models.CharField(max_length=15)),
                ('skype_name_number', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.company')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Company_Staff.vendor')),
            ],
        ),
    ]
