# Generated by Django 4.2.3 on 2024-01-05 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0009_paymenttermsupdates'),
        ('Company_Staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customercontactperson',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='login_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.paymentterms'),
        ),
        migrations.AlterField(
            model_name='vendorhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails'),
        ),
        migrations.AlterField(
            model_name='vendorhistory',
            name='login_details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
        migrations.DeleteModel(
            name='PaymentTerm',
        ),
    ]
