# Generated by Django 4.2.3 on 2024-01-17 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0003_vendor_baddress_vendor_battention_vendor_bcity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
