# Generated by Django 4.2.3 on 2024-01-17 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0009_paymenttermsupdates'),
        ('Company_Staff', '0004_alter_vendor_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='billing_attention',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_fax',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_pin_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='billing_state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Register_Login.companydetails'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='currency',
            field=models.CharField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='department',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='designation',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='first_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='gst_treatment',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='last_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='login_details',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='opening_balance_type',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='pan_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='payment_term',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Register_Login.paymentterms'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='salutation',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_attention',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_city',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_country',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_fax',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_pin_code',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_state',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='skype_name_number',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='source_of_supply',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_display_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='vendor_status',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
