# Generated by Django 4.2.3 on 2024-01-20 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0010_company_payment_term'),
        ('Company_Staff', '0008_alter_vendor_company_alter_vendor_login_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='payment_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Register_Login.company_payment_term'),
        ),
    ]
