# Generated by Django 4.2.3 on 2024-01-23 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0010_company_payment_term'),
        ('Company_Staff', '0009_alter_vendor_payment_term'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerContactPerson',
            new_name='VendorContactPerson',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='baddress',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='battention',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bcity',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bcountry',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bfax',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bphone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bpin',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bstate',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bstreet',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='bzip',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='saddress',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='sattention',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='scity',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='scountry',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='sfax',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='sphone',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='spin',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='sstate',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='sstreet',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='szip',
        ),
    ]
