# Generated by Django 4.2.3 on 2024-02-03 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Register_Login', '0010_company_payment_term'),
        ('Company_Staff', '0011_vendor_comments_table_login_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor_doc_upload_table',
            name='login_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Register_Login.logindetails'),
        ),
        migrations.AlterField(
            model_name='vendorhistory',
            name='action',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
