# Generated by Django 4.2.3 on 2024-02-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0012_vendor_doc_upload_table_login_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='gst_treatment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
