# Generated by Django 4.2.3 on 2024-02-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0013_alter_vendor_gst_treatment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='source_of_supply',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
