# Generated by Django 4.2.3 on 2024-02-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0016_alter_vendor_billing_attention_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='billing_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
