# Generated by Django 4.2.3 on 2024-02-16 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0017_alter_vendor_billing_address_alter_vendor_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
